name: task runner

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install libsndfile1
      run: sudo apt-get install libsndfile1
    - name: List TTS available models
      run: |
        tts --list_models
    - name: Run tts CLI
      run: |
        tts --text "In the news today - Afghanistan, COVID 19, Corona Virus, Australia, India, and the USA." --out_path ./output/output1.wav
    # --model_name "<type>/<language>/<dataset>/<model_name>" 
    # - name: Run the overall task
    #   run: |
    #     python task.py