name: task runner

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: coqui-ai/TTS
        path: coqui_tts

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Install missing dependencies
    #   run: |
    #     python -m pip install --upgrade mecab-python3==1.0.3
    #     python -m pip install --upgrade unidic-lite==1.0.8
    
    - name: Install libsndfile1
      run: sudo apt-get install libsndfile1
    
    - name: List TTS available models
      run: |
        tts --list_models

    - name: List TTS available models with checkout repo
      run: |
        ./TTS/bin/synthesize.py --list_models
      working-directory: coqui_tts
    # - name: Run tts CLI - tts_models/en/ljspeech/tacotron2-DCA
    #   run: |
    #     tts --text "In the news today - Afghanistan, COVID 19, Corona Virus, Australia, India, and the USA." \
    #       --model_name tts_models/en/ljspeech/tacotron2-DCA \
    #       --out_path ./ttsoutput/ljspeech_tacotron2_DCA.wav
    # # - name: Run tts CLI - tts_models/en/vctk/vits
    # #   run: |
    # #     tts --text "In the news today - Afghanistan, COVID 19, Corona Virus, Australia, India, and the USA." \
    # #       --model_name tts_models/en/vctk/vits \
    # #       --out_path ./ttsoutput/vctk_vits.wav
    # # - name: Run tts CLI - tts_models/en/ek1/tacotron2
    # #   run: |
    # #     tts --text "In the news today - Afghanistan, COVID 19, Corona Virus, Australia, India, and the USA. Also, AWS, EC2, Amazon, Facebook, and Google." \
    # #       --model_name tts_models/en/ek1/tacotron2 \
    # #       --out_path ./ttsoutput/ek1_tacotron2.wav
    # - name: Run tts CLI - tts_models/en/ljspeech/tacotron2-DDC
    #   run: |
    #     tts --text "In the news today - Afghanistan, COVID 19, Corona Virus, Australia, India, and the USA. Also, AWS, EC2, Amazon, Facebook, and Google." \
    #       --model_name tts_models/en/ljspeech/tacotron2-DDC \
    #       --out_path ./ttsoutput/ljspeech_tacotron2_ddc.wav
    # - name: Run tts CLI - tts_models/en/ljspeech/glow-tts
    #   run: |
    #     tts --text "In the news today - Afghanistan, COVID 19, Corona Virus, Australia, India, and the USA. Also, AWS, EC2, Amazon, Facebook, and Google." \
    #       --model_name tts_models/en/ljspeech/glow-tts \
    #       --out_path ./ttsoutput/ljspeech_glow_tts.wav
    # - name: Run tts CLI - tts_models/en/ljspeech/speedy-speech-wn
    #   run: |
    #     tts --text "In the news today - Afghanistan, COVID 19, Corona Virus, Australia, India, and the USA. Also, AWS, EC2, Amazon, Facebook, and Google." \
    #       --model_name tts_models/en/ljspeech/speedy-speech-wn \
    #       --out_path ./ttsoutput/ljspeech_speedy_speech_wn.wav
    # - name: Run tts CLI - tts_models/en/ljspeech/vits
    #   run: |
    #     tts --text "In the news today - Afghanistan, COVID 19, Corona Virus, Australia, India, and the USA. Also, AWS, EC2, Amazon, Facebook, and Google." \
    #       --model_name tts_models/en/ljspeech/vits \
    #       --out_path ./ttsoutput/ljspeech_vits.wav
    # - name: Run tts CLI - tts_models/en/sam/tacotron-DDC
    #   run: |
    #     tts --text "In the news today - Afghanistan, COVID 19, Corona Virus, Australia, India, and the USA. Also, AWS, EC2, Amazon, Facebook, and Google." \
    #       --model_name tts_models/en/sam/tacotron-DDC \
    #       --out_path ./ttsoutput/sam_tacotron_DDC.wav
    # - name: Run tts CLI - tts_models/en/vctk/sc-glow-tts - p244
    #   run: |
    #     tts --text "In the news today - Afghanistan, COVID 19, Corona Virus, Australia, India, and the USA. Also, AWS, EC2, Amazon, Facebook, and Google." \
    #       --model_name tts_models/en/vctk/sc-glow-tts \
    #       --speaker_idx p244 \
    #       --out_path ./ttsoutput/vctk_sc_glow_tts.wav
    # - name: Run tts CLI - tts_models/en/ljspeech/tacotron2-DDC_ph
    #   run: |
    #     tts --text "In the news today - Afghanistan, COVID 19, Corona Virus, Australia, India, and the USA. Also, AWS, EC2, Amazon, Facebook, and Google." \
    #       --model_name tts_models/en/ljspeech/tacotron2-DDC_ph \
    #       --out_path ./ttsoutput/ljspeech_tacotron2_DCC_ph.wav
    # - name: Run tts CLI - tts_models/en/ljspeech/tacotron2-DDC_ph - directly pass phonemes
    #   run: |
    #     tts --text "ˈɪ n ð ə n j ˈu z t ə d ˈeɪ æ f ɡ ˈæ n ɪ s t ˌæ n | k ˈoʊ v ɪ d n ˈaɪ n t ˈi n | k ɚ ˈoʊ n ə v ˈaɪ ɹ ə s | ɔ s t ɹ ˈeɪ l j ə | ˈɪ n d i ə | ˈæ n d ð ə ˌʌ s ə ‖" \
    #       --model_name tts_models/en/ljspeech/tacotron2-DDC_ph \
    #       --out_path ./ttsoutput/phonemes_ljspeech_tacotron2_DCC_ph.wav
    - name: Run tts library through torch Hub
      run: |
        python test.py
    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: 'ttsoutput'
    # - name: Run the overall task
    #   run: |
    #     python task.py